<?php

  $text_script = array(
  "site_title" => "South Sudan - A man-made catastrophe",

  "metadata" => "South Sudan South Sudan is silently suffering. 1.7 million South Sudanese have been forced to flee their homes. Famine is threatening. Share this website, show the world that the people of South Sudan MUST not be forgotten. bit.ly/SthSudan",

  "title" => "A MAN-MADE CATASTROPHE",

  "subtitle" => "A multimedia journey through South Sudan",

  "title_para" => "Last December, a political disagreement turned violent and turned the world’s newest country upside-down.",

  "scrolldown" => "Scroll<br/>down",

  "page1" => array (
      "para1" => "The crisis in South Sudan started on 15 December 2013. Political tensions spilled over, and there was fighting on the streets of Juba, the capital city. The violence quickly spread across the country.",

      "para2" => "Since then, South Sudan has been caught in the grip of a crisis defined by horrendous
      <strong>violence</strong>, massive <strong>displacement</strong> and now, the threat of terrible <strong>famine</strong>."
  ),

  "page2" => array(
      "subtitle" => "John's Story",
      "title"    => "THE VIOLENCE",
      "para1"    => "Within weeks, thousands of people had been killed or wounded. Aid groups received horrific reports of innocent civilians murdered in their homes and in hospitals, of unspeakable violence against women and children.",
      "para2"    => "One in seven people have been forced from their homes. Inside the country, 1.3 million remain displaced, and 450,000 have left for the safety of neighbouring countries.",
      "para3"    => "Within months, the dream of South Sudan – the world’s youngest country – has turned into a nightmare.",
      "para4"   => "**John Mamer** lived with his family in Bor, a town in the centre of the country, on the eastern bank of the River Nile. Soon after the conflict started in Juba, Bor exploded into violence. Hundreds of people were killed, and most of the town forced to flee.",
      "para5"   => "Listen to John as he remembers the night that Bor fell.",
      "transcript_title"  => "TRANSCRIPT",
      "transcript_loc"    => "inc/johns-stories.inc",
      "interactive_map_title"   => "Interactive Map",
      "para6"   => "John’s family fled <strong class='highlight'>Bor</strong>, crossing the River Nile to find safety in <strong class='highlight'>Mingkaman</strong>.",
      "para7"   => "Learn more about the violence and displacement that has gripped South Sudan since December 2013. ",
      "para8" => "Double click on the map to <strong class='highlight'>zoom in</strong>",
      "disclaimer" => "Disclaimer: \"The boundaries and names shown and the designations used on this map do not imply official endorsement or acceptance by the United Nations. Final boundary between the Republic of Sudan and the Republic of South Sudan has not yet been determined. Final status of the Abyei area is not yet determined.\"",
      "para9" => "Nine months of violence has exposed many families to a life of fear, sickness, hunger, displacement and destitution."
  ),

  "page3" => array(
    "subtitle" => "Mary's Story",
    "title" => "Displacement",
    "spiel" => "Displacement is not just about leaving your home. It is about being entirely cut off from your life. Imagine having to run from your home, taking with you only the few things you are able to carry.",
    "slide1" => "John’s family now lives in Mingkaman, South Sudan’s largest site for internally displaced people. **Mary**, his wife, lives with six of their seven children and their seven grandchildren.",
    "slide2" =>
    "Mary worries about food. Though aid agencies are providing food, hunger is a growing concern.

To complicate matters, floods, continued violence, and lack of funds are making it harder for aid agencies to deliver.",
    "slide3" =>
    "###Watch as Mary talks about life in the displacement site at Mingkaman.

&quot;They took everything,&quot; she says, of the armed groups that destroyed her home in Bor. &quot;Now, here we are living without shelter.&quot;",
    "slide4" => "The violence and displacement that has swept across South Sudan prevented farmers from sowing crops. Now that the rains have arrived, it is too late. The UN and its partners now fear that large swathes of South Sudan could face famine."

  ),

  "page4" => array(
    "title" => "The threat of famine",
    "spiel" => "Life in Mingkaman and Bor is a daily struggle. But further north in Unity State, the fear of hunger has – for some – given way to the reality of starvation.",
    "slide1" => "To make matters worse, the rainy season has brought with it flooding, worsening sanitation and exposing malnourished children to diseases like cholera.

Aid groups working in Bentiu, the capital of Unity State, say that children are now dying every day because of severe malnutrition and other diseases.",
    "slide2" =>
    "Families like **Nyagol Mayiel’s** trekked for days to reach Bentiu, eating wild grass, water lilies or whatever they could find along the way.

&quot;We came from Leer (about 100 kilometres to the South) on foot. I was carrying the younger baby and the others were walking. We walked for five days to get here,&quot; she said.",
    "slide3" =>
    "Nyagol’s one-and-a-half year old daughter, <strong class='highlight'>Nyataba</strong>, is being treated for malnutrition.

She is now stabilizing, after days of coughing, vomiting and diarrhoea. Her younger brother did not receive treatment in time to save his life.",

    "slide4" =>
    "The humanitarian crisis in South Sudan has caused immense human suffering.

The UN estimates that 3.9 million people – just under 35 per cent of the entire population – don't have enough to eat. The risk of this turning into widespread famine is high and increasing every day.",
    "slide5" => "If people had been able to plant their crops and if markets hadn’t been destroyed, the threat of famine could have been avoided.",

    "map_text" =>
    "<h3>A CRISIS OF DEVASTATING PROPORTIONS</h3>
<p style='font-size: 18px;'>This map shows the severity of food insecurity in South Sudan. Right now, much of the north is classified as being in the Emergency Phase – the final phase before famine. In these areas, at least 1 in 5 households face extreme food consumption gaps, resulting in very high acute malnutrition or excess mortality.</p>
<p style='font-size: 18px;'>In some areas, however, there are reports that as many as 50 per cent of children are severely malnourished.</p>

<p style='font-size: 18px'><span class='glyphicon glyphicon-info-sign'></span><span id='map2-instruction'>Double click on the map to <strong class='highlight'>zoom in</strong><span>.</p>",
    "disclaimer" => "Disclaimer: The boundaries and names shown and the designations used on this map do not imply official endorsement or acceptance by the United Nations. Final boundary between the Republic of Sudan and the Republic of South Sudan has not yet been determined. Final status of the Abyei area is not yet determined.",
    "slide6_a" => "Action must be taken now. <strong>235,000 children</strong> will need treatment for severe acute malnutrition this year.",
    "slide6_b" => "This is <strong>twice</strong> as many as last year.",
    "slide6_c" => "Without treatment, up to <strong>50,000 children</strong> may die by the end of the year.",
    "slide6_d" => "This is a <strong><u>man-made crisis</u></strong>.",
    "slide_disclaimer" => "Disclaimer: This image has been digitally altered.",

    "toby_quote" => "&quot;The tragedy of South Sudan is that this crisis is man-made. The displacement and the violence did not need to happen, the suffering we're seeing wasn't inevitable. And now, we face the threat of famine. If it comes, it will also be man-made.&quot;",
    "toby_source" => "- Toby Lanzer, Humanitarian Coordinator, South Sudan"



  ),

  "cta" => array(
    "title" => "What can you do?",
    "cta1" => "Take a stand",
    "cta1_text" => "The crisis in South Sudan needs to end now, before more people are killed or displaced and before famine takes hold.",
    "tweet" => "Stop the fighting. RT if you agree, #SouthSudan deserves better.",


    "tweet_new" => "The humanitarian community stands ready to deliver aid in #SouthSudan, but more funding is needed. We MUST avert famine",
    "tweet_civilians" => "Attacks on civilians MUST stop in #SouthSudan. So must the recruitment of child soldiers. They deserve a childhood",

    "donate" => "Make a Donation",
    "donate_spiel" => "We know you care. Make a donation and help aid groups provide food, medical care and shelter for the people caught up in this man-made crisis.",
    "donate_button" => "Donate",

    "more_info" => "Find out more",
    "more_info_text" => "Visit OCHA’s South Sudan website to put the humanitarian crisis in context",
    "more_info_button" => "Visit Website",
    "credits" => "Photos: OCHA/Jacob Zocherman, OCHA/Ally Ngethi, UNICEF/Peru, UNICEF/Holt; Video: OCHA/Peter Murimi. The designations employed and the presentation of material on the map do not imply the expression of any opinion whatsoever on the part of the Secretariat of the United Nations concerning the legal status of any country, territory, city or area or of its authorities, or concerning the delimitation of its frontiers or boundaries."


  )

);


?>
