<?php

  $text_script = array(
  "site_title" => "Una catástrofe provocada por el hombre | Un viaje multimedia a través de Sudán del Sur",

  "metadata" => "Sudán del Sur está sufriendo en silencio. 1.7 millones de sursudaneses se han visto obligados a huir de sus hogares. La hambruna amenaza su presencia en los márgenes. Comparte esta página web y muéstrale al mundo que la gente de Sudán del Sur no debe ser olvidada. bit.ly/SthSudan",

  "title" => "UNA CATÁSTROFE HECHA POR EL HOMBRE",

  "subtitle" => "Un viaje multimedia a través de Sudán del Sur",

  "title_para" => "El pasado diciembre, un desacuerdo político trastornó al estado más joven del mundo, sumergiéndolo en la violencia.",

  "scrolldown" => "Desplazar<br/>hacia abajo",

  "page1" => array (
      "para1" => "La crisis en Sudán del Sur comenzó el 15 de diciembre del 2013. Tensiones políticas se degeneraron, desbordándose en violentos combates en las calles de Juba, la capital del país. La violencia se expandió rápidamente por todo el país.",

      "para2" => "Desde entonces, Sudán del Sur se ha visto atrapado en las garras de una crisis de una <strong>violencia</strong> horrenda, <strong>desplazamientos</strong> masivos y ahora, la terrible <strong>amenaza</strong> de una hambruna."
  ),

  "page2" => array(
      "subtitle" => "La historia de Juan",
      "title"    => "LA VIOLENCIA",
      "para1"    => "A cabo de unas pocas semanas, miles de personas habían muerto o habían sido heridas. Los equipos de ayuda humanitaria recibieron reportes aterradores de civiles asesinados en sus casas y en hospitales, y de una violencia incalificable en contra de mujeres y niños.",
      "para2"    => "Una de cada siete personas ha tenido que abandonar su hogar. En el interior del país, 1.3 millones de personas siguen desplazadas y 450,000 han cruzado las fronteras en busca de mayor seguridad en países vecinos.",
      "para3"    => "En cuestión de solo unos meses, el sueño de Sudán del Sur – el estado más joven del mundo - se ha convertido en una pesadilla.",
      "para4"   => "**John Mamer** vivía con su familia en Bor, una ciudad en el centro del país, en la orilla oriental del río Nilo. Poco después de que el conflicto empezara en Juba, la violencia estalló en Bor.  Cientos de personas fueron asesinadas y la mayoría de los habitantes de la cuidad tuvieron que huir.",
      "para5"   => "Escuche a Juan contar sobre la noche en que cayó Bor.",
      "transcript_title"  => "TRANSCRIPCIÓN",
      "transcript_loc"    => "inc/johns-stories-es.inc",
      "interactive_map_title"   => "MAPA INTERACTIVO",
      "para6"   => "La familia de John huyó de <strong class='highlight'>Bor</strong>, cruzando el río Nilo para encontrar refugio en <strong class='highlight'>Mingkaman</strong>.",
      "para7"   => "Para saber más información sobre la violencia y el desplazamiento que se ha apoderado de Sudán del Sur desde diciembre de 2013",
      "para8" => "Haga doble clic en el mapa para <strong class='highlight'>zoom in</strong>",

      "disclaimer" => "Descargo de responsabilidades: &quot;Los límites, nombres y títulos utilizados ​​en este mapa no implican su apoyo o aceptación oficial por las Naciones Unidas. La frontera definitiva entre la República de Sudán y la República de Sudán del Sur aún no ha sido determinada. El estatuto final de la área de Abyei no ha sido determinado.&quot;",
      "para9" => "Nueve meses de violencia ha dejado a numerosas familias expuestas al miedo, la enfermedad, el hambre, desplazamientos y a la miseria."
  ),

  "page3" => array(
    "subtitle" => "La historia de Mary",
    "title" => "DESPLAZAMIENTO",
    "spiel" => "Ser desplazado no se trata sólo de tener que abandonar su casa. Es tener que dejar atrás su vida entera por completo. Imagínese tener que salir corriendo de su casa, llevándose tan sólo las pocas cosas que puede cargar.",
    "slide1" => "La familia de John ahora vive en Mingkaman, el área para personas desplazadas internas más grande de Sudán del Sur. **Mary**, su esposa, vive con seis de sus siete hijos y sus siete nietos.",

    "slide2" =>
    "La falta de comida preocupa a Mary. Aunque las agencias de ayuda humanitarias están distribuyendo alimentos, el hambre sigue siendo una preocupación creciente.

Las inundaciones, la violencia continua, y la falta de fondos hacen la tarea de las agencias humanitarias aún más difícil.",
    "slide3" =>
    "###En este video, Mary habla de su vida diaria en el área de desplazados en Mingkaman.

&quot;Se llevaron todo,&quot; dice ella, sobre los grupos armados que destruyeron su casa en Bor. &quot;Ahora, aquí vivimos sin refugio.&quot;",
    "slide4" => "La violencia y el desplazamiento que ha arrasado Sudán del Sur impidió que los agricultores pudieran sembrar sus cultivos. Ahora que la temporada de lluvias ha llegado, ya es demasiado tarde. La ONU y sus asociados temen que una gran parte del país pueda enfrentarse a una hambruna."

  ),

  "page4" => array(
    "title" => "LA AMENAZA DE LA HAMBRUNA",
    "spiel" => "La vida en Mingkaman y Bor es una lucha diaria. Pero un poco más al norte en el estado de Unity, la gente ha empezado a morir de hambre.",
    "slide1" => "La temporada de lluvias ha empeorado la situación y ha traído consigo inundaciones que han empeorado el saneamiento, exponiendo a niños, que ya tienen problemas de desnutrición, a más enfermedades como el cólera.

Los equipos humanitarios que trabajan en Bentiu, la capital del estado de Unity, reportan que niños están muriendo diariamente de desnutrición severa y otras enfermedades.",
    "slide2" =>

    "Familias como la de **Nyagol Mayiel** caminaron durante días para llegar a Bentiu, comiendo hierbas salvajes, lirios de agua o cualquier cosa que encontraban en el camino.

&quot;Veníamos de Leer (a unos 100 kilómetros al sur) a pie. Yo llevaba al bebé más chico y los demás iban caminando. Caminamos durante cinco días para llegar aquí,&quot; explica ella.",
    "slide3" =>
    "<strong class='highlight'>Nyataba</strong>, la hija de Nyagol de un año y medio , está recibiendo tratamiento contra la desnutrición. Su condición es estable, después de días de tos, vómito y diarrea. Su hermano más chico no fue tratado a tiempo para que pudiese sobrevivir.",

    "slide4" =>
    "La crisis humanitaria en Sudán del Sur ha causado inmenso sufrimiento humano.

La ONU estima que 3.9 millones de personas – alrededor de 35 por ciento de la población total - no tienen suficiente para comer. El riesgo de que el país caiga en una hambruna es extremadamente elevado y crece cada día.",
    "slide5" => "Si hubiera sido posible plantar cultivos y si los mercados no hubieran sido destruidos, la amenaza de una hambruna hubiera podido ser evitada.",

    "map_text" =>
    "<h3>Una crisis de proporciones devastadoras</h3>
<p style='font-size: 18px;'>Este mapa muestra la gravedad de la inseguridad alimentaria en Sudán del Sur. En este momento, gran parte del norte está clasificado en Estado de Emergencia - la última fase antes de una declaración de hambruna. En estas regiones, al menos 1 de cada 5 hogares afrontan faltas extremas de consumo de alimentos, resultando en una muy alta desnutrición aguda o mortalidad.</p>
<p style='font-size: 18px;'>En algunas áreas, informan que hasta un 50 por ciento de los niños están gravemente desnutridos. Haga doble clic en el mapa para ampliarlo.</p>

<p style='font-size: 18px'><span class='glyphicon glyphicon-info-sign'></span><span id='map2-instruction'>Haga doble clic en el mapa para <strong class='highlight'>zoom in</strong><span>.</p>",
    "disclaimer" => "Descargo de responsabilidades: \"Los límites, nombre y títulos utilizados ​​en este mapa no implican su apoyo o aceptación oficial por las Naciones Unidas. La frontera definitiva entre la República de Sudán y la República de Sudán del Sur aún no ha sido determinada. El estatuto final de la área de Abyei no ha sido determinado.\"",
    "slide6_a" => "Se debe de actuar ya.  <strong>235,000 niños</strong> necesitarán tratamiento contra desnutrición aguda este año.",
    "slide6_b" => "Esto es el <strong>doble</strong> que el año pasado.",
    "slide6_c" => "Sin tratamiento, hasta <strong>50,000 niños</strong> podrían morir antes del final del año.",
    "slide6_d" => "Esta es <strong>una crisis provocada por el hombre</strong>.",
    "slide_disclaimer" => "Disclaimer: This image has been digitally altered.",

    "toby_quote" => "&quot;La tragedia de Sudán del Sur es que esta crisis está provocada por el hombre. El desplazamiento y la violencia no tenía por qué ocurrir, el sufrimiento que estamos viendo no era inevitable. Y ahora, nos estamos enfrentando a la amenaza de una hambruna. Si llega, también habrá sido provocada por el hombre.&quot;",
    "toby_source" => "- Toby Lanzer, Coordinador de Asuntos Humanitarios en Sudán del Sur"



  ),

  "cta" => array(
    "title" => "¿QUÉ PUEDES HACER?",
    "cta1" => "Pronúnciate",
    "cta1_text" => "La crisis en Sudán del Sur  tiene que acabarse ya, antes de que más personas sean asesinadas o desplazadas y antes de que la hambruna pueda llegar.",
    "tweet" => "Paren los combates. RT si estás de acuerdo, #SudandelSur se merece algo mejor.",


    "tweet_new" => "La comunidad humanitaria está lista para entregar ayuda en #SudandelSur, pero se necesitan $232m. TENEMOS q evitar una hambruna.",
    "tweet_civilians" => "La comunidad humanitaria está lista para entregar ayuda en #SudandelSur, pero se necesitan $232m. TENEMOS q evitar una hambruna.",

    "donate" => "Haga una donación",
    "donate_spiel" => "Sabemos que le importa esta crisis. Haga una donación y ayude a las organizaciones de ayuda humanitaria a proporcionar alimentos, atención médica y refugio para las personas atrapadas en esta crisis provocada por el hombre.",
    "donate_button" => "Haga una donación",

    "more_info" => "Para saber más",
    "more_info_text" => "Visite la página web de OCHA en Sudán del Sur para saber más sobre el contexto de la crisis humanitaria en el país.",
    "more_info_button" => "Ir a la página web",

    "credits" => "Fotos: OCHA / Jacob Zocherman, OCHA / Aliado Ngethi, UNICEF / Perú, UNICEF / Holt; Vídeo: OCHA / Peter Murimi. Los límites, nombre y títulos utilizados ​​en este mapa no implican su apoyo o aceptación oficial por las Naciones Unidas."


  )

);


?>
