<?php
$johns_transcript="
The fighting began at 10PM and continued until morning. They were coming from three directions, so it was hard to escape.

Innocent civilians were targeted. They killed the vulnerable—women, children, the elderly and the disabled. We stayed inside until morning, until the situation got worse. We left Bor at exactly 6AM, and headed for the port.

There was a lot of shooting. We were rescued from the port and sailed to the west bank of the River Nile, toMingkaman.

The day I returned to Bor to check on my home and property, I couldn’t help but cry. There were deadbodies lying all over the town. Everything was burnt to ashes.

Bor was a ghost town, and everything was a mess. I decided to return to Mingkaman immediately.

On the first day of our settlement in Mingkaman the host community donated food to us. Later, humanitarianagencies came.

Life here in Bor is miserable compared to Mingkaman. People who are living here depend on food rationsfrom Mingkaman, where the United Nations provides aid.

The conflict we are facing today is man-made, and I believe that the only remedy must also be a man-madesolution.
";
?>
