<p>Les combats ont commencé à 22 heures, et ont continué

jusqu’au matin. Ils arrivaient de trois directions, alors il 

était difficile de s’échapper.</p>

<p>Ils ont ciblé des civils innocents. Ils ont tué les plus 

vulnérables : les femmes, les enfants, les personnes âgées 

et les handicapés. Nous sommes restés jusqu’au matin, 

quand la situation a empiré. Nous avons quitté Bor à 6 

heures du matin exactement, et nous sommes dirigés 

vers le port.</p>

<p>Il y avait beaucoup de coups de feu. Nous avons été 

rescapés du port et avons navigué vers la rive gauche du 

Nil, vers Mingkaman.</p>

<p>Le jour où je suis retourné à Bor pour voir ma maison et 

mes possessions, je n’ai pas pu m’empêcher de pleurer. 

Toute la ville était jonchée de cadavres. Tout avait été 

réduit en cendres.</p>

<p>Bor était une ville fantôme, dans un état chaotique. J’ai 

décidé de retourner à Mingkaman immédiatement.

Le premier jour que nous avons passé à Mingkaman, la 

communauté-hôte nous a donné de quoi manger. Plus 

tard, les agences humanitaires sont arrivées.</p>

<p>La vie à Bor est épouvantable, comparé à Mingkaman. Les 

gens qui vivent ici dépendent des rations de nourriture 

venant de Mingkaman, où les Nations Unies livrent 

l’assistance.</p>

<p>Le conflit auquel nous faisons face aujourd’hui a été 

créé par l’Homme, et je crois que la seule solution devra 

également venir de l’Homme.</p>