<?php
$johns_transcript="
Los combates empezaron a las diez de la noche y duraron hasta la mañana. Venían de tres direcciones, por lo que era difícil escapar.

Atacaron a civiles inocentes. Mataron a la gente vulnerable: mujeres, niños, ancianos y discapacitados. Nos quedamos adentro hasta la mañana, hasta que la situación empeoró. Nos fuimos de Bor exactamente a las seis de la mañana y nos dirigimos hacia el puerto.

Había muchos disparos. Nos rescataron en el puerto y navegamos a la orilla oeste del río Nilo, hacia Mingkaman.

El día que regresé a Bor para ver mi casa y mi propiedad, no pude contener mis lágrimas. La ciudad estaba repleta de cadáveres. Todo había sido reducido a cenizas.

Bor era una ciudad fantasma, en un estado caótico. Decidí regresar a Mingkaman inmediatamente. En nuestro primer día en Mingkaman, la comunidad nos dio de comer. Las agencias humanitarias llegaron más tarde.

La vida aquí en Bor es miserable en comparación con Mingkaman. La gente que vive aquí depende de las raciones de alimentos de Mingkaman, donde las Naciones Unidas da ayuda.

El conflicto que tenemos hoy fue creado por el hombre y creo que la única solución tendrá que venir también del hombre.
";
?>
